{"errorMessage": "An error occurred (MessageRejected) when calling the SendEmail operation: Email address is not verified. The following identities failed the check in region US-EAST-2: yirongwang03@gmail.com", "errorType": "MessageRejected", "requestId": "ceb4d157-c5fa-463e-bff7-d0dafbd671c7", "stackTrace": ["  File \"/var/task/app.py\", line 43, in handler\n    ses.send_email(\n", "  File \"/var/task/botocore/client.py\", line 570, in _api_call\n    return self._make_api_call(operation_name, kwargs)\n", "  File \"/var/task/botocore/context.py\", line 123, in wrapper\n    return func(*args, **kwargs)\n", "  File \"/var/task/botocore/client.py\", line 1031, in _make_api_call\n    raise error_class(parsed_response, operation_name)\n"]}